name = "apple-rag-mcp"
main = "src/index.ts"
compatibility_date = "2024-07-01"

# Production-ready configuration - aligned with working apple-rag-mcp-production
routes = [
  { pattern = "mcp.apple-rag.com/*", zone_name = "apple-rag.com" }
]

# Optimized monitoring for production MCP server
[observability]
enabled = true
head_sampling_rate = 0.5  # Balanced sampling for production monitoring

[[kv_namespaces]]
binding = "TOKENS"
id = "bff2091c27b342e0b768ec98759a6605"
