name: Publish MCP Server

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (without v prefix)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.0.0/mcp-publisher_1.0.0_linux_amd64.tar.gz" | tar xz mcp-publisher
          sudo mv mcp-publisher /usr/local/bin/

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            # Extract version from tag (remove 'v' prefix)
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION"

      - name: Update server.json version
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          echo "Updating server.json to version: $VERSION"
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" server.json
          
          # Verify the update
          grep "\"version\":" server.json

      - name: Validate server.json
        run: |
          # Basic JSON validation
          if ! python3 -m json.tool server.json > /dev/null; then
            echo "❌ Invalid JSON in server.json"
            exit 1
          fi
          echo "✅ server.json is valid JSON"

      - name: Login to MCP Registry
        run: |
          mcp-publisher login dns --domain apple-rag.com --private-key "${{ secrets.MCP_PRIVATE_KEY }}"

      - name: Publish to MCP Registry
        run: |
          echo "🚀 Publishing to MCP Registry..."
          mcp-publisher publish
          echo "✅ Successfully published to MCP Registry!"
          echo "🔗 View: https://registry.modelcontextprotocol.io/v0/servers?search=com.apple-rag/mcp-server"